/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Base/Accordion.vue')['default']
    AccordionItem: typeof import('./src/components/Base/AccordionItem.vue')['default']
    AddFilesDropdown: typeof import('./src/components/AddFilesDropdown.vue')['default']
    Badge: typeof import('./src/components/Base/Badge.vue')['default']
    BaseButton: typeof import('./src/components/Base/BaseButton.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Container: typeof import('./src/components/Base/Container.vue')['default']
    CTASection: typeof import('./src/components/Sections/CTASection.vue')['default']
    DetailListItem: typeof import('./src/components/DetailListItem.vue')['default']
    FAQSection: typeof import('./src/components/Sections/FAQSection.vue')['default']
    FeaturebaseChangelog: typeof import('./src/components/FeaturebaseChangelog.vue')['default']
    FeaturebaseFeedback: typeof import('./src/components/FeaturebaseFeedback.vue')['default']
    FeaturebaseUserConnect: typeof import('./src/components/FeaturebaseUserConnect.vue')['default']
    FeatureSection: typeof import('./src/components/Sections/FeatureSection.vue')['default']
    FileListItem: typeof import('./src/components/FileListItem.vue')['default']
    FolderListItem: typeof import('./src/components/FolderListItem.vue')['default']
    FooterSection: typeof import('./src/components/Sections/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/Sections/HeroSection.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    ModalVideo: typeof import('./src/components/Modal/ModalVideo.vue')['default']
    Navbar: typeof import('./src/components/Header/Navbar.vue')['default']
    PriceSection: typeof import('./src/components/Sections/PriceSection.vue')['default']
    RecoveryUploadCard: typeof import('./src/components/RecoveryUploadCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./src/components/Separator.vue')['default']
    StarterSubscriptionCard: typeof import('./src/components/StarterSubscriptionCard.vue')['default']
    SubscribeButton: typeof import('./src/components/SubscribeButton.vue')['default']
    SubscriptionToggle: typeof import('./src/components/Base/SubscriptionToggle.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    UploadCard: typeof import('./src/components/UploadCard.vue')['default']
    UploadListFileItem: typeof import('./src/components/UploadListFileItem.vue')['default']
    UploadListFolderItem: typeof import('./src/components/UploadListFolderItem.vue')['default']
    UploadRecoveryFlow: typeof import('./src/components/UploadRecoveryFlow.vue')['default']
    UserDropDownMenu: typeof import('./src/components/UserDropDownMenu.vue')['default']
    VerifyTransactionCard: typeof import('./src/components/VerifyTransactionCard.vue')['default']
  }
}
