# Creates a test release of the Quickbyte Transfer app when a commit
# is pushed to the desktop-transfer-test-release branch
# This is meant for on-demand testing of the release during development. You can force
# a push to the transfer-app-test-release branch whenever you want to test.
# The releases created from this pipeline include the current date and can be deleted
# to avoid noise in the release page.

name: 'Test release of Quickbyte Transfer desktop app'

on:
  push:
    branches:
        - desktop-transfer-test-release

defaults:
  run:
    shell: bash
    working-directory: desktop/gui
jobs:
  get-date:
    name: Get current data
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    outputs:
      date: ${{ steps.date.outputs.date }}

  build_app:
    needs: get-date
    permissions:
      contents: write
    uses: ./.github/workflows/build-release-transfer-app-common.yml
    with:
        app_name: 'Quickbyte Transfer Dev'
        bundle_identifier: 'io.quickbyte.desktoptransfer.dev'
        server_base_url: 'https://quickbyte-staging.up.railway.app'
        should_release: true
        release_prefix: test-${{ needs.get-date.outputs.date }}-
        prerelease: true
        create_artifacts: false
    secrets:
        google_client_id: ${{ secrets.DESKTOP_TRANSFER_DEV_GOOGLE_CLIENT_ID }}
        google_client_secret: ${{ secrets.DESKTOP_TRANSFER_DEV_GOOGLE_CLIENT_SECRET }}
        release_github_token: ${{ secrets.DESKTOP_TRANSFER_APP_RELEASE_GITHUB_TOKEN }}
        tauri_private_key: ${{ secrets.TAURI_PRIVATE_KEY }}
        tauri_private_key_password: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
